GET  http://localhost:3001/api/links

###
POST http://localhost:3001/api/links
Content-Type: application/json

{
    "links" : "http:www.walmart.com",
    "comment" : "is this working"

}

###
PATCH  http://localhost:3001/api/links/0df12366-98f3-46cf-ac09-943fb1a988f9/
Content-Type: application/json

{
    "comment" : "new"
}
